### ISSUE TITLE
Menu (briefly) disappears when a nav element is clicked on

### ISSUE THREAD

**Issue by tnorthcutt** [mrjasonweaver/flexnav#12]
I have flexnav applied to a `<ul>` element. When I click on an `<a>` element within that `<ul>` (this is at a large viewport with the menu not collapsed), the entire `<ul>` disappears, but on page load is visible again. I've confirmed using Chrome's inspector that a display: none; is applied to the `<ul>` element.

This seems to be because of the code starting on line 54:

```
//Closes nav menu after links clicked/touched
$this.find('a').click(function() {                                           
   $this.hide();                                                            
});
```

Which seems to target any `<a>` element inside the element that flexnav is applied to, and when clicked, hides the element flexnav is applied to. However, this isn't the behavior I observe at http://jasonweaver.name/lab/flexiblenavigation/ and isn't behavior I've observed when using flexnav in the past (before it was packaged as a jQuery plugin).

Any suggestions?

**Comment by mrjasonweaver** [comment]
I stuck that bit in there because of a feature request. Here's the another closed issue with the same question: https://github.com/indyplanets/flexnav/issues/4. 

I would remove that bit if you're having problems. Doesn't need to be in there to function properly.

Also, I'm behind on releasing a major overhaul for this plugin. Read more in my comments here: https://github.com/indyplanets/flexnav/issues/11

**Comment by tnorthcutt** [comment]
Thanks, that did fix it.
