### ISSUE TITLE
Two break points

### ISSUE THREAD

**Issue by leanda** [mrjasonweaver/flexnav#19]
Is it possible to have two breakpoints? 

For example, for mobile the menu it would be in it's toggle down state, for a smaller screen it would go to the across the top menu and then for a widescreen there would be another breakpoint to take it back to an accordion style lefthand menu.

Thanks

**Comment by mrjasonweaver** [comment]
Yes, it's possible but I wouldn't want to add in that much complexity to this simple proof-of-concept. Better to fork it and add in your modifications.

**Comment by leanda** [comment]
Thanks, also I'm having a problem with the sub-menus. It's also happening on your demo, so I'm not sure if it's the intended behaviour. When you click the a Sub Item #1 and it reveals the Sub 2 Items it also reveals the the Sub Item #2 menu. Is there anyway I can stop this happening?

Thanks again.

**Comment by mrjasonweaver** [comment]
I've just updated this plugin with bug fixes and support for IE7/8. Let me know if you're still having problems. Thanks.

**Comment by leanda** [comment]
Good stuff Jason. The only thing I can see now is a problem where sometimes the menus are dropping down on :hover in the mobile state when viewed on the desktop. I've been having a fiddle around with the CSS but I can't seem to solve it. Any ideas?

**Comment by mrjasonweaver** [comment]
@leanda  Yeah, that's a "bug" I've been trying to iron out. It's not a problem on touch screens because there are no user hover actions. And most of the time a normal user would have the mobile view on a touch screen. I'd like to get that fixed in the near future. There is also a bug if a user is on a small screen, opens the mobile menu and scrolls, the menu closes. This because (I suspect) the window resize event fires and as a result, closes the menu.

**Comment by mrjasonweaver** [comment]
@leanda Opened issue https://github.com/indyplanets/flexnav/issues/24
