### ISSUE TITLE
Hover not working on desktop - only click

### ISSUE THREAD

**Issue by lesliecdubs** [mrjasonweaver/flexnav#59]
I'm not able to simply hover to expand sub-menu items on desktop -- the user has to click to view more items. I'm working at http://development.lesliebass.com/. 

Is this a known bug, or do you think there's a conflict in my site causing this behavior?

**Comment by lesliecdubs** [comment]
Sorry -- issue resolved. User error! Thanks.

**Comment by mrjasonweaver** [comment]
@lbass2 Cool site! Let me know when it's launched. I'm working on a site gallery.

**Comment by tsmith512** [comment]
@lbass2 I know this issue is quite old, but I'm having a similar situation. What was the user error you found? Because I think I may have done something similar...

**Comment by tsmith512** [comment]
Ah. Okay. I also figured it out. Or at least, my particular problem, in case this helps anyone: I wasn't sure what `data-breakpoint` was for, since I am using CSS to hide the menu when it isn't needed. So I didn't have it set. Hover won't work unless the `data-breakpoint` is set and the window is wider than that, and I didn't see that explained in the docs (which I lightly skimmed, so I likely missed it). If you set `data-breakpoint` either in your markup directly or programmatically, it'll work. I can't add that attribute since it is autogenerated, but I did this:

``` js
$('.main-menu > ul').attr('data-breakpoint', 780).flexNav();
```

And now it is working like the example site for me.
